[global]
repo1-type=s3
repo1-s3-endpoint=minio:9000
repo1-s3-bucket=pgbackrest
repo1-s3-region=us-east-1
repo1-s3-key=minioadmin
repo1-s3-key-secret=minioadmin123
repo1-s3-uri-style=path
repo1-storage-verify-tls=n
repo1-path=/pgbackrest
repo1-retention-full=2
log-path=/tmp/pgbackrest-log
process-max=2

[poc-demo]
pg1-path=/var/lib/postgresql/data
pg1-port=5432
